// ── Context Sorter — Markdown page renderers ─────────────────────────────────
// Pure string-builders. No state, no I/O — every renderer takes the data it
// needs and returns the final Markdown.
'use strict';

const {
  TYPE_LABELS,
  CATEGORY_EMOJI,
  SYNTHESIS_SESSION_CAP,
  SYNTHESIS_FILE_CAP,
} = require('./constants');

const {
  _isoDate,
  _yamlString,
  _firstUserMessage,
  _lastAssistantMessage,
  _sessionTypePrefix,
} = require('./util');

interface _RelatedRef {
  sid:   string;
  slug:  string;
  title: string;
}

interface _FileMember {
  abs:         string;
  basename:    string;
  title:       string;
  category:    string;
  topics:      string[];
  tags:        string[];
  keywords:    string[];
  sensitivity: string;
  mtime:       number;
}

function _renderSessionPage(
  s: any,
  slug: string,
  related: ReadonlyArray<_RelatedRef> = [],
): string {
  const cat = s.category || 'general';
  const emoji = CATEGORY_EMOJI[cat] || CATEGORY_EMOJI.general;
  const tags: string[] = Array.isArray(s.tags) ? s.tags : [];
  const tagLine = tags.length ? tags.map((t) => '#' + t).join(' ') : '';
  const created = _isoDate(s.createdAt);
  const messageCount = (s.messages || []).length;
  const wd = s.workingDir || s.cwd || '';
  const sensitivity = (s.sensitivity || 'public') as string;
  const sensitivityLine = sensitivity === 'public'
    ? ''
    : `\n> ⚠ **Sensitivity:** \`${sensitivity}\` — confirm-gate active in YHA UI.`;
  const firstMsg = _firstUserMessage(s);
  const lastAss  = _lastAssistantMessage(s);

  // Frontmatter `related` exposes the wikilink targets to Obsidian's Dataview
  // / graph view as proper YAML so users can build queries against the
  // backlink network directly.
  const relatedSlugs = related.map((r) => r.slug);

  const keywords: string[] = Array.isArray(s.keywords) ? s.keywords : [];
  const fmLines = [
    '---',
    `id: ${_yamlString(s.id)}`,
    `title: ${_yamlString(s.name || '(untitled session)')}`,
    `category: ${_yamlString(cat)}`,
    `tags: [${tags.map((t) => _yamlString(t)).join(', ')}]`,
    // Phase 4.3 — surface keywords[] in the Markdown frontmatter so Obsidian
    // / Dataview can build queries against the semantic-search axis the
    // categorizer now produces. Empty when the LLM didn't return any (e.g.
    // legacy sessions or notes-shortcut path).
    `keywords: [${keywords.map((k) => _yamlString(k)).join(', ')}]`,
    `nameSource: ${_yamlString(s._nameSource || 'unknown')}`,
    `sensitivity: ${_yamlString(sensitivity)}`,
    `createdAt: ${_yamlString(created)}`,
    `workingDir: ${_yamlString(wd)}`,
    `messageCount: ${messageCount}`,
    `slug: ${_yamlString(slug)}`,
    `related: [${relatedSlugs.map((sl) => _yamlString(sl)).join(', ')}]`,
    '---',
  ];

  // Render the related-list in two flavours so the page is useful both for
  // human reading and for Obsidian's graph view:
  //   • Markdown bullet list with `[[../sessions/<slug>|Title]]` links
  //   • A trailing inline `[[<slug>]]` block (parsed by Obsidian even if the
  //     bullet list is collapsed) — keeps the graph populated.
  const relatedSection = related.length === 0
    ? '- _No related sessions found._'
    : related
        .map((r) => `- [[../sessions/${r.slug}|${r.title}]]`)
        .join('\n');
  // Inline-link sentinel: ensures every wikilink is parsed even if the bullet
  // list above gets folded. Hidden in HTML preview via the `>` quote, visible
  // in source mode for the curious.
  const inlineLinks = related.length === 0
    ? ''
    : '> ' + related.map((r) => `[[${r.slug}]]`).join(' ');

  return [
    fmLines.join('\n'),
    '',
    `# ${s.name || '(untitled session)'}`,
    '',
    `> **Session:** \`${s.id}\`  `,
    `> **Created:** ${created.slice(0, 10) || '—'}  `,
    // Link the synthesis page (the `<cat>-synthesis.md` written next to
    // this category dir). The legacy `_category.md` page is gated off
    // (sorter/runner.ts:115) so the previous wikilink resolved to nothing.
    `> **Category:** [[by-category/${cat}/${cat}-synthesis|${emoji} ${cat}]]  `,
    tagLine ? `> **Tags:** ${tagLine}` : '',
    sensitivityLine,
    '',
    '## History',
    '',
    firstMsg
      ? `- First message: "${firstMsg.replace(/\n+/g, ' ')}"`
      : '- _No messages extractable._',
    // Capture the last assistant turn alongside the first user message so
    // the synthesis page reflects both the question and the resolution
    // (~5–10× the search-index value vs. user-turn-only). Audit 2026-05-10.
    lastAss
      ? `- Last reply: "${lastAss.replace(/\n+/g, ' ')}"`
      : null,
    '',
    '## Related Sessions',
    '',
    relatedSection,
    inlineLinks ? '' : null,
    inlineLinks || null,
    '',
    '---',
    `*Generated by ContextGenerator · ${new Date().toISOString().slice(0, 10)}*`,
    '',
  ].filter((l) => l !== null).join('\n');
}

function _renderCategoryIndex(cat: string, members: Array<{ sid: string; s: any; slug: string }>): string {
  const emoji = CATEGORY_EMOJI[cat] || CATEGORY_EMOJI.general;
  const sorted = [...members].sort((a, b) =>
    (b.s.updatedAt ?? b.s.lastUsed ?? 0) - (a.s.updatedAt ?? a.s.lastUsed ?? 0));
  const lines = [
    '---',
    `category: ${_yamlString(cat)}`,
    `members: ${sorted.length}`,
    '---',
    '',
    `# ${emoji} ${cat}`,
    '',
    `Sessions in this category: **${sorted.length}**.`,
    '',
  ];
  for (const { s, slug } of sorted) {
    const date = _isoDate(s.updatedAt ?? s.createdAt).slice(0, 10);
    const tier = s.sensitivity && s.sensitivity !== 'public' ? ` 🔒` : '';
    lines.push(`- [[../../sessions/${slug}|${s.name || s.id}]] · ${date}${tier}`);
  }
  lines.push('', `*Generated ${new Date().toISOString().slice(0, 10)}*`, '');
  return lines.join('\n');
}

function _renderTypeIndex(prefix: string, members: Array<{ sid: string; s: any; slug: string }>): string {
  const label = TYPE_LABELS[prefix as keyof typeof TYPE_LABELS] || 'Other';
  const sorted = [...members].sort((a, b) =>
    (b.s.updatedAt ?? b.s.lastUsed ?? 0) - (a.s.updatedAt ?? a.s.lastUsed ?? 0));
  const lines = [
    '---',
    `type: ${_yamlString(prefix)}`,
    `members: ${sorted.length}`,
    '---',
    '',
    `# ${label}`,
    '',
    `Sessions of type \`${prefix}\`: **${sorted.length}**.`,
    '',
  ];
  for (const { s, slug } of sorted) {
    const date = _isoDate(s.updatedAt ?? s.createdAt).slice(0, 10);
    const cat = s.category || 'general';
    lines.push(`- [[../sessions/${slug}|${s.name || s.id}]] · ${date} · \`${cat}\``);
  }
  lines.push('', `*Generated ${new Date().toISOString().slice(0, 10)}*`, '');
  return lines.join('\n');
}

function _renderDateIndex(quarter: string, members: Array<{ sid: string; s: any; slug: string }>): string {
  const sorted = [...members].sort((a, b) =>
    (b.s.createdAt ?? 0) - (a.s.createdAt ?? 0));
  const lines = [
    '---',
    `quarter: ${_yamlString(quarter)}`,
    `members: ${sorted.length}`,
    '---',
    '',
    `# ${quarter}`,
    '',
    `Sessions created in **${quarter}**: ${sorted.length}.`,
    '',
  ];
  for (const { s, slug } of sorted) {
    const date = _isoDate(s.createdAt).slice(0, 10);
    const cat = s.category || 'general';
    lines.push(`- ${date} — [[../sessions/${slug}|${s.name || s.id}]] · \`${cat}\``);
  }
  lines.push('', `*Generated ${new Date().toISOString().slice(0, 10)}*`, '');
  return lines.join('\n');
}

function _renderMasterIndex(all: Array<{ sid: string; s: any; slug: string }>): string {
  const byCat = new Map<string, number>();
  const byType = new Map<string, number>();
  for (const m of all) {
    const c = m.s.category || 'general';
    byCat.set(c, (byCat.get(c) || 0) + 1);
    const tp = _sessionTypePrefix(m.sid);
    byType.set(tp, (byType.get(tp) || 0) + 1);
  }
  const lines = [
    '---',
    `total: ${all.length}`,
    `generatedAt: ${_yamlString(new Date().toISOString())}`,
    '---',
    '',
    '# YHA — Generated Knowledge Base',
    '',
    `Total sessions on disk: **${all.length}**.`,
    '',
    '## By category',
    '',
  ];
  for (const [cat, n] of [...byCat.entries()].sort((a, b) => b[1] - a[1])) {
    const e = CATEGORY_EMOJI[cat] || CATEGORY_EMOJI.general;
    // Link the active synthesis page; `_category.md` is gated off (see
    // sorter/runner.ts:115).
    lines.push(`- [[by-category/${cat}/${cat}-synthesis|${e} ${cat}]] — ${n}`);
  }
  lines.push('', '## By type', '');
  for (const [tp, n] of [...byType.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- [[by-type/${tp}|${TYPE_LABELS[tp as keyof typeof TYPE_LABELS] || tp}]] — ${n}`);
  }
  lines.push('', `*Auto-generated · ${new Date().toISOString()}*`, '');
  return lines.join('\n');
}

function _renderStats(all: Array<{ sid: string; s: any; slug: string }>, runStats: {
  lastRunAt: number | null;
  lastRunFilesWritten: number;
  lifetimeFilesWritten: number;
}): string {
  const sensitive = all.filter((m) => m.s.sensitivity && m.s.sensitivity !== 'public').length;
  const tagged    = all.filter((m) => Array.isArray(m.s.tags) && m.s.tags.length > 0).length;
  return [
    '---',
    `total: ${all.length}`,
    `tagged: ${tagged}`,
    `sensitive: ${sensitive}`,
    `generatedAt: ${_yamlString(new Date().toISOString())}`,
    '---',
    '',
    '# Stats',
    '',
    `- Total session pages: **${all.length}**`,
    `- Tagged sessions: **${tagged}**`,
    `- Sensitive (private/system): **${sensitive}**`,
    `- Files written in last run: **${runStats.lastRunFilesWritten}**`,
    `- Lifetime files written: **${runStats.lifetimeFilesWritten}**`,
    `- Last run: ${runStats.lastRunAt ? new Date(runStats.lastRunAt).toISOString() : 'never'}`,
    '',
  ].join('\n');
}

// ── Phase 4.2 — Synthesis pages ──────────────────────────────────────────────
// Cross-category aggregator that lists, for each topic slug, the sessions and
// files that touch it. Sessions hit a slug when `s.category === slug`; files
// hit when their primary `category` is the slug OR when their LLM-derived
// `topics: [...]` contains it.
//
// Rendered to `by-category/<cat>/<cat>-synthesis.md` (the basename is
// per-category so Obsidian's graph view shows each synthesis hub as a
// distinct node — when every page was just `synthesis.md` the graph
// collapsed all 24 hubs to a single ambiguous "synthesis" label).
// The old `_category.md` is being phased out (see Step 3 of the cleanup
// plan); both are still written transitionally so existing wikilinks keep
// resolving until the deprecation cutover.

function _renderSynthesisPage(
  cat:      string,
  sessions: ReadonlyArray<{ sid: string; s: any; slug: string }>,
  files:    ReadonlyArray<_FileMember>,
): string {
  const emoji = CATEGORY_EMOJI[cat] || CATEGORY_EMOJI.general;

  const sessionsSorted = [...sessions].sort((a, b) =>
    (b.s.updatedAt ?? b.s.lastUsed ?? 0) - (a.s.updatedAt ?? a.s.lastUsed ?? 0)
  ).slice(0, SYNTHESIS_SESSION_CAP);
  const filesSorted = [...files].sort((a, b) => b.mtime - a.mtime).slice(0, SYNTHESIS_FILE_CAP);

  // Aggregate tag + keyword cloud (top 20 each, by frequency).
  const tagCounts: Map<string, number> = new Map();
  const kwCounts:  Map<string, number> = new Map();
  for (const m of sessionsSorted) {
    for (const t of (m.s.tags || [])) {
      tagCounts.set(t, (tagCounts.get(t) || 0) + 1);
    }
    // Sessions don't have keywords[] yet (Phase 4.3) — skip silently.
  }
  for (const f of filesSorted) {
    for (const t of f.tags)     tagCounts.set(t, (tagCounts.get(t) || 0) + 1);
    for (const k of f.keywords) kwCounts.set(k,  (kwCounts.get(k)  || 0) + 1);
  }
  const topTags = [...tagCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 20).map(([t]) => t);
  const topKws  = [...kwCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 20).map(([k]) => k);

  const lines: string[] = [
    '---',
    `category: ${_yamlString(cat)}`,
    `type: synthesis`,
    `sessions: ${sessionsSorted.length}`,
    `files: ${filesSorted.length}`,
    `generatedAt: ${_yamlString(new Date().toISOString())}`,
    '---',
    '',
    `# ${emoji} ${cat} — Synthesis`,
    '',
    `> Auto-generated cross-reference. Lists every session and note touching this topic, ` +
      `linked into a single browse-able index. Both the read-only \`_category.md\` (sessions only) ` +
      `and this page are rebuilt on each sorter pass — \`_category.md\` is the legacy ` +
      `quality baseline, this page is the one we iterate on.`,
    '',
  ];

  if (sessionsSorted.length === 0 && filesSorted.length === 0) {
    lines.push('_No items in this category yet._', '');
    lines.push(`*Auto-generated · ${new Date().toISOString()}*`, '');
    return lines.join('\n');
  }

  if (sessionsSorted.length > 0) {
    lines.push(`## Sessions (${sessionsSorted.length})`, '');
    for (const { s, slug } of sessionsSorted) {
      const date = _isoDate(s.updatedAt ?? s.createdAt).slice(0, 10);
      const tier = s.sensitivity && s.sensitivity !== 'public' ? ' 🔒' : '';
      lines.push(`- [[../../sessions/${slug}|${s.name || s.id}]] · ${date}${tier}`);
    }
    lines.push('');
  }

  if (filesSorted.length > 0) {
    lines.push(`## Notes (${filesSorted.length})`, '');
    for (const f of filesSorted) {
      const date = _isoDate(f.mtime).slice(0, 10);
      const tier = f.sensitivity && f.sensitivity !== 'public' ? ' 🔒' : '';
      // Bare-basename wikilinks resolve vault-wide in Obsidian regardless of
      // whether the user remapped `docs/keep-notes/` to `Google Keep/` or
      // `keep-notes/` on the vault side. The trade-off: ambiguous basenames
      // (rare in keep-notes since filenames carry titles) appear flagged in
      // Obsidian's link tooltip.
      lines.push(`- [[${f.basename}|${f.title}]] · ${date}${tier}`);
    }
    lines.push('');
  }

  if (topTags.length > 0) {
    lines.push(`## Tags`, '', topTags.map((t) => '`#' + t + '`').join(' '), '');
  }
  if (topKws.length > 0) {
    lines.push(`## Keywords`, '', topKws.map((k) => '`' + k + '`').join(' · '), '');
  }

  lines.push(`*Auto-generated · ${new Date().toISOString()}*`, '');
  return lines.join('\n');
}

module.exports = {
  _renderSessionPage,
  _renderCategoryIndex,
  _renderTypeIndex,
  _renderDateIndex,
  _renderMasterIndex,
  _renderStats,
  _renderSynthesisPage,
};
